// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {flasher} from '../models';
import {assetserver} from '../models';
import {board} from '../models';
import {options} from '../models';
import {ethernet} from '../models';
import {fs} from '../models';
import {learn} from '../models';
import {wifi} from '../models';

export function ApplyBoardUpdate(arg1:boolean,arg2:string):Promise<any>;

export function CheckAndApplyUpdate(arg1:boolean):Promise<void>;

export function CheckBoardUpdate(arg1:boolean,arg2:string):Promise<string>;

export function ConnectToWiFi(arg1:string,arg2:string):Promise<void>;

export function CreateFolder(arg1:string):Promise<void>;

export function DeleteRefreshToken(arg1:string):Promise<void>;

export function DisconnectWiFi():Promise<void>;

export function ExportApp(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function Flash(arg1:flasher.OSImageRelease,arg2:boolean):Promise<void>;

export function ForwardNonUIPort(arg1:number):Promise<void>;

export function GetAboutMessage():Promise<string>;

export function GetAssetMiddleware():Promise<assetserver.Middleware>;

export function GetAvailableFreeSpace():Promise<number>;

export function GetBoardList():Promise<Array<board.Board>>;

export function GetBoardName():Promise<string>;

export function GetBoardUpdateLogs(arg1:string):Promise<void>;

export function GetConnectionName():Promise<any>;

export function GetCurrentVersion():Promise<string>;

export function GetErrorFormatter():Promise<options.ErrorFormatter>;

export function GetEthStatus():Promise<ethernet.EthStatus>;

export function GetFeatureFlags():Promise<Array<string>>;

export function GetFileContent(arg1:string):Promise<string>;

export function GetFileTree(arg1:string):Promise<fs.FSNode>;

export function GetInternetStatus():Promise<boolean>;

export function GetKeyboardLayout():Promise<string>;

export function GetLearnResource(arg1:learn.LearnResourceID):Promise<learn.FullLearnResource>;

export function GetLearnResourceList():Promise<Array<learn.LearnResourceEntry>>;

export function GetOSImageVersion():Promise<string>;

export function GetOrchestratorURL():Promise<string>;

export function GetRefreshToken(arg1:string):Promise<string>;

export function GetTags():Promise<Array<learn.Tag>>;

export function GetTitle():Promise<string>;

export function GetWiFiStatus():Promise<wifi.WifiStatus>;

export function HandleSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function ImportApp():Promise<string>;

export function ImportAppFromPath(arg1:string):Promise<string>;

export function InferOrchestratorURL():Promise<string>;

export function IsBoard():Promise<boolean>;

export function IsUserPartitionPreservationSupported(arg1:string,arg2:string):Promise<boolean>;

export function IsUserPasswordSet():Promise<boolean>;

export function ListAvailableOSImages():Promise<Array<flasher.OSImageRelease>>;

export function ListKeyboardLayouts():Promise<Array<board.KeyboardLayout>>;

export function ListSSIDs():Promise<Array<string>>;

export function NeedsImageUpdate():Promise<boolean>;

export function NewVersion():Promise<string>;

export function OnUrlOpen(arg1:string):Promise<void>;

export function OpenBoardTerminal():Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenUIWhenReady(arg1:number,arg2:number):Promise<void>;

export function RemoveFile(arg1:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function SaveTempFile(arg1:string,arg2:Array<number>):Promise<string>;

export function SelectBoard(arg1:string,arg2:string):Promise<void>;

export function SetBoardName(arg1:string):Promise<void>;

export function SetKeyboardLayout(arg1:string):Promise<void>;

export function SetRefreshToken(arg1:string,arg2:string):Promise<void>;

export function SetUserPassword(arg1:string):Promise<void>;

export function WriteFileContent(arg1:string,arg2:string):Promise<void>;
