enableStrictSsl: false

nodeLinker: node-modules

npmScopes:
  bcmi-labs:
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - ./dev-utils/dev-config/scripts/plugin-env-npm.js

yarnPath: .yarn/releases/yarn-4.17.1.cjs
