/* eslint-disable simple-import-sort/imports */
/* eslint-disable prettier/prettier */
// AUTO-GENERATED by scripts/sync-seti-icons.js — do not edit by hand.
import { FunctionComponent, SVGProps } from 'react';

import Icon_R from './svg/R.svg?react';
import Icon_audio from './svg/audio.svg?react';
import Icon_babel from './svg/babel.svg?react';
import Icon_bazel from './svg/bazel.svg?react';
import Icon_bower from './svg/bower.svg?react';
import Icon_c from './svg/c.svg?react';
import Icon_clojure from './svg/clojure.svg?react';
import Icon_code_climate from './svg/code-climate.svg?react';
import Icon_config from './svg/config.svg?react';
import Icon_cpp from './svg/cpp.svg?react';
import Icon_css from './svg/css.svg?react';
import Icon_csv from './svg/csv.svg?react';
import Icon_cu from './svg/cu.svg?react';
import Icon_dart from './svg/dart.svg?react';
import Icon_db from './svg/db.svg?react';
import Icon_default from './svg/default.svg?react';
import Icon_docker from './svg/docker.svg?react';
import Icon_editorconfig from './svg/editorconfig.svg?react';
import Icon_elixir from './svg/elixir.svg?react';
import Icon_elm from './svg/elm.svg?react';
import Icon_eslint from './svg/eslint.svg?react';
import Icon_ethereum from './svg/ethereum.svg?react';
import Icon_favicon from './svg/favicon.svg?react';
import Icon_firebase from './svg/firebase.svg?react';
import Icon_font from './svg/font.svg?react';
import Icon_git from './svg/git.svg?react';
import Icon_git_ignore from './svg/git_ignore.svg?react';
import Icon_gitlab from './svg/gitlab.svg?react';
import Icon_go from './svg/go.svg?react';
import Icon_graphql from './svg/graphql.svg?react';
import Icon_grunt from './svg/grunt.svg?react';
import Icon_gulp from './svg/gulp.svg?react';
import Icon_haskell from './svg/haskell.svg?react';
import Icon_heroku from './svg/heroku.svg?react';
import Icon_html from './svg/html.svg?react';
import Icon_illustrator from './svg/illustrator.svg?react';
import Icon_image from './svg/image.svg?react';
import Icon_java from './svg/java.svg?react';
import Icon_javascript from './svg/javascript.svg?react';
import Icon_jenkins from './svg/jenkins.svg?react';
import Icon_json from './svg/json.svg?react';
import Icon_karma from './svg/karma.svg?react';
import Icon_kotlin from './svg/kotlin.svg?react';
import Icon_less from './svg/less.svg?react';
import Icon_license from './svg/license.svg?react';
import Icon_lock from './svg/lock.svg?react';
import Icon_lua from './svg/lua.svg?react';
import Icon_makefile from './svg/makefile.svg?react';
import Icon_markdown from './svg/markdown.svg?react';
import Icon_maven from './svg/maven.svg?react';
import Icon_notebook from './svg/notebook.svg?react';
import Icon_npm from './svg/npm.svg?react';
import Icon_npm_ignored from './svg/npm_ignored.svg?react';
import Icon_pdf from './svg/pdf.svg?react';
import Icon_perl from './svg/perl.svg?react';
import Icon_photoshop from './svg/photoshop.svg?react';
import Icon_php from './svg/php.svg?react';
import Icon_platformio from './svg/platformio.svg?react';
import Icon_powershell from './svg/powershell.svg?react';
import Icon_prisma from './svg/prisma.svg?react';
import Icon_python from './svg/python.svg?react';
import Icon_react from './svg/react.svg?react';
import Icon_rollup from './svg/rollup.svg?react';
import Icon_ruby from './svg/ruby.svg?react';
import Icon_rust from './svg/rust.svg?react';
import Icon_sass from './svg/sass.svg?react';
import Icon_scala from './svg/scala.svg?react';
import Icon_shell from './svg/shell.svg?react';
import Icon_stylus from './svg/stylus.svg?react';
import Icon_svelte from './svg/svelte.svg?react';
import Icon_svg from './svg/svg.svg?react';
import Icon_swift from './svg/swift.svg?react';
import Icon_terraform from './svg/terraform.svg?react';
import Icon_tex from './svg/tex.svg?react';
import Icon_todo from './svg/todo.svg?react';
import Icon_tsconfig from './svg/tsconfig.svg?react';
import Icon_typescript from './svg/typescript.svg?react';
import Icon_video from './svg/video.svg?react';
import Icon_vite from './svg/vite.svg?react';
import Icon_vue from './svg/vue.svg?react';
import Icon_wasm from './svg/wasm.svg?react';
import Icon_wat from './svg/wat.svg?react';
import Icon_webpack from './svg/webpack.svg?react';
import Icon_windows from './svg/windows.svg?react';
import Icon_xml from './svg/xml.svg?react';
import Icon_yarn from './svg/yarn.svg?react';
import Icon_yml from './svg/yml.svg?react';
import Icon_zip from './svg/zip.svg?react';

export type PackSvgComponent = FunctionComponent<
  SVGProps<SVGSVGElement> & { title?: string | undefined }
>;

export const packIconComponents: Record<string, PackSvgComponent> = {
  'R': Icon_R,
  'audio': Icon_audio,
  'babel': Icon_babel,
  'bazel': Icon_bazel,
  'bower': Icon_bower,
  'c': Icon_c,
  'clojure': Icon_clojure,
  'code-climate': Icon_code_climate,
  'config': Icon_config,
  'cpp': Icon_cpp,
  'css': Icon_css,
  'csv': Icon_csv,
  'cu': Icon_cu,
  'dart': Icon_dart,
  'db': Icon_db,
  'default': Icon_default,
  'docker': Icon_docker,
  'editorconfig': Icon_editorconfig,
  'elixir': Icon_elixir,
  'elm': Icon_elm,
  'eslint': Icon_eslint,
  'ethereum': Icon_ethereum,
  'favicon': Icon_favicon,
  'firebase': Icon_firebase,
  'font': Icon_font,
  'git': Icon_git,
  'git_ignore': Icon_git_ignore,
  'gitlab': Icon_gitlab,
  'go': Icon_go,
  'graphql': Icon_graphql,
  'grunt': Icon_grunt,
  'gulp': Icon_gulp,
  'haskell': Icon_haskell,
  'heroku': Icon_heroku,
  'html': Icon_html,
  'illustrator': Icon_illustrator,
  'image': Icon_image,
  'java': Icon_java,
  'javascript': Icon_javascript,
  'jenkins': Icon_jenkins,
  'json': Icon_json,
  'karma': Icon_karma,
  'kotlin': Icon_kotlin,
  'less': Icon_less,
  'license': Icon_license,
  'lock': Icon_lock,
  'lua': Icon_lua,
  'makefile': Icon_makefile,
  'markdown': Icon_markdown,
  'maven': Icon_maven,
  'notebook': Icon_notebook,
  'npm': Icon_npm,
  'npm_ignored': Icon_npm_ignored,
  'pdf': Icon_pdf,
  'perl': Icon_perl,
  'photoshop': Icon_photoshop,
  'php': Icon_php,
  'platformio': Icon_platformio,
  'powershell': Icon_powershell,
  'prisma': Icon_prisma,
  'python': Icon_python,
  'react': Icon_react,
  'rollup': Icon_rollup,
  'ruby': Icon_ruby,
  'rust': Icon_rust,
  'sass': Icon_sass,
  'scala': Icon_scala,
  'shell': Icon_shell,
  'stylus': Icon_stylus,
  'svelte': Icon_svelte,
  'svg': Icon_svg,
  'swift': Icon_swift,
  'terraform': Icon_terraform,
  'tex': Icon_tex,
  'todo': Icon_todo,
  'tsconfig': Icon_tsconfig,
  'typescript': Icon_typescript,
  'video': Icon_video,
  'vite': Icon_vite,
  'vue': Icon_vue,
  'wasm': Icon_wasm,
  'wat': Icon_wat,
  'webpack': Icon_webpack,
  'windows': Icon_windows,
  'xml': Icon_xml,
  'yarn': Icon_yarn,
  'yml': Icon_yml,
  'zip': Icon_zip,
};
